CREATE TABLE [dbo].[Referents]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL,
	[FirstName] NVARCHAR(255) NOT NULL,
	[LastName] NVARCHAR(255) NULL,
	[ClientId] UNIQUEIDENTIFIER NULL,
	[Area] NVARCHAR(255) NULL,
	[EmailAddress] NVARCHAR(255) NULL,
	[LandlineNumber] VARCHAR(50) NULL,
	[MobilePhone] VARCHAR(50) NULL,
	[Secretary] NVARCHAR(255) NULL
)
