CREATE TABLE [dbo].[Users]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Email] NVARCHAR(255) NOT NULL,
	[PasswordHash] VARCHAR(32) NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	[Role] VARCHAR(255) NOT NULL
)
